readme: "https://docs.google.com/document/d/1EMSvr-loBBWwaehb4oOjKlt1ZpZEujNA0lhTs7xi0cg/edit"
metrics:
  - "Acappella clearness"
  - "Attack and release"
  - "Dynamics"
  - "Frequency range"
  - "Presence of effects"
